const PDFDocument = require('pdfkit');

/**
 * Generate a forensic PDF report and pipe it to a writable stream (e.g. res)
 * @param {Object} opts
 * @param {Array}  opts.evidenceList   - populated evidence documents
 * @param {Array}  opts.custodyLogs    - custody log documents
 * @param {Object} opts.generatedBy    - user object
 * @param {Object} opts.params         - report filter params
 * @param {Stream} opts.outputStream   - writable stream to pipe PDF into
 */
const generateForensicPDF = ({ evidenceList, custodyLogs, generatedBy, params, outputStream }) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
  doc.pipe(outputStream);

  const COLORS = {
    primary: '#000000',
    accent: '#000000',
    danger: '#000000',
    success: '#000000',
    muted: '#555555',
    light: '#ffffff',
    border: '#000000',
  };

  const pageWidth = doc.page.width - 100; // account for margins

  // ── HEADER ───────────────────────────────────────────────────────────────
  doc.rect(50, 40, pageWidth, 70).stroke(COLORS.border);
  doc.fillColor(COLORS.primary)
    .font('Helvetica-Bold').fontSize(18)
    .text('Digital Evidence Chain of Custody System', 65, 55);
  doc.font('Helvetica').fontSize(11)
    .text('FORENSIC EVIDENCE REPORT', 65, 78);
  doc.fontSize(8).fillColor(COLORS.muted)
    .text('CONFIDENTIAL — AUTHORIZED PERSONNEL ONLY', 65, 95);

  doc.fillColor(COLORS.primary);
  doc.moveDown(4);

  // ── REPORT METADATA ──────────────────────────────────────────────────────
  const metaY = 130;
  doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.primary)
    .text('Report Information', 50, metaY);
  doc.moveTo(50, metaY + 16).lineTo(50 + pageWidth, metaY + 16).stroke(COLORS.border);

  const metaRows = [
    ['Generated By', generatedBy.name],
    ['Role', generatedBy.role.toUpperCase()],
    ['Generated At', new Date().toUTCString()],
    ['Report Type', (params.reportType || 'full').toUpperCase()],
    ['Case Filter', params.caseId || 'All Cases'],
    ['Date Range', params.dateFrom && params.dateTo ? `${params.dateFrom} to ${params.dateTo}` : 'All Dates'],
    ['Total Evidence Records', String(evidenceList.length)],
  ];

  let y = metaY + 24;
  metaRows.forEach(([label, value], i) => {
    if (i % 2 === 0) doc.rect(50, y, pageWidth, 18).fill('#f6f6f6');
    doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.muted).text(label, 58, y + 5);
    doc.font('Helvetica').fontSize(9).fillColor('#222').text(value, 200, y + 5);
    y += 18;
  });

  doc.moveDown(2);

  // ── EVIDENCE SUMMARY TABLE ───────────────────────────────────────────────
  doc.addPage();
  doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.primary)
    .text('Evidence Summary', 50, 50);
  doc.moveTo(50, 68).lineTo(50 + pageWidth, 68).lineWidth(2).stroke(COLORS.primary);

  // Table header
  const cols = [
    { label: 'Evidence Name', x: 50, w: 150 },
    { label: 'Case ID', x: 205, w: 90 },
    { label: 'Type', x: 300, w: 90 },
    { label: 'Custodian', x: 395, w: 100 },
    { label: 'Integrity', x: 498, w: 55 },
  ];

  y = 78;
  doc.rect(50, y, pageWidth, 18).stroke(COLORS.border);
  cols.forEach(col => {
    doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.primary)
      .text(col.label, col.x + 4, y + 5, { width: col.w - 6 });
  });
  y += 18;

  evidenceList.forEach((ev, idx) => {
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 50;
    }
    if (idx % 2 === 0) doc.rect(50, y, pageWidth, 18).fill('#f6f6f6');
    const custodianName = ev.currentCustodian?.name || '—';
    const rows = [
      ev.name,
      ev.caseId,
      ev.fileType,
      custodianName,
      ev.integrityStatus.toUpperCase(),
    ];
    cols.forEach((col, ci) => {
      const color = '#000000';
      doc.font(ci === 4 ? 'Helvetica-Bold' : 'Helvetica')
        .fontSize(8).fillColor(color)
        .text(rows[ci], col.x + 4, y + 5, { width: col.w - 6, ellipsis: true });
    });
    y += 18;
  });

  // ── DETAILED EVIDENCE RECORDS ────────────────────────────────────────────
  evidenceList.forEach((ev) => {
    doc.addPage();
    const custodianName = ev.currentCustodian?.name || '—';
    const uploaderName = ev.uploadedBy?.name || '—';

    // Evidence header band
    doc.rect(50, 40, pageWidth, 32).stroke(COLORS.border);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(COLORS.primary)
      .text(ev.name, 60, 52, { width: pageWidth - 20 });

    y = 90;

    // Details grid
    doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.primary).text('Evidence Details', 50, y);
    y += 16;

    const details = [
      ['Evidence ID', String(ev._id)],
      ['Case ID', ev.caseId],
      ['File Name', ev.originalName || ev.fileName],
      ['File Size', ev.fileSizeFormatted || `${ev.fileSize} bytes`],
      ['File Type', ev.fileType],
      ['Acquisition Date', ev.acquisitionDate ? new Date(ev.acquisitionDate).toUTCString() : '—'],
      ['Uploaded By', uploaderName],
      ['Uploaded At', new Date(ev.createdAt).toUTCString()],
      ['Current Custodian', custodianName],
      ['Status', ev.status.toUpperCase()],
      ['Integrity Status', ev.integrityStatus.toUpperCase()],
      ['Last Integrity Check', ev.integrityLastChecked ? new Date(ev.integrityLastChecked).toUTCString() : 'Never'],
    ];

    details.forEach(([label, value], i) => {
      if (i % 2 === 0) doc.rect(50, y, pageWidth, 16).fill('#f6f6f6');
      doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.muted).text(label, 58, y + 4, { width: 140 });
      doc.font('Helvetica').fontSize(8).fillColor('#111').text(String(value), 200, y + 4, { width: pageWidth - 155 });
      y += 16;
    });

    // Description
    if (ev.description) {
      y += 6;
      doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.primary).text('Description', 50, y);
      y += 14;
      doc.font('Helvetica').fontSize(8).fillColor('#333')
        .text(ev.description, 50, y, { width: pageWidth });
      y += doc.heightOfString(ev.description, { width: pageWidth }) + 10;
    }

    // SHA-256 Hash
    y += 6;
    doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.primary).text('SHA-256 Hash', 50, y);
    y += 14;
    doc.rect(50, y, pageWidth, 22).stroke(COLORS.border);
    doc.font('Helvetica').fontSize(7.5).fillColor(COLORS.primary)
      .text(ev.hash, 56, y + 7, { width: pageWidth - 10 });
    y += 30;

    // Custody chain
    const evLogs = custodyLogs.filter(l => String(l.evidence) === String(ev._id) ||
      (l.evidence?._id && String(l.evidence._id) === String(ev._id)));

    doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.primary).text(`Chain of Custody (${evLogs.length} events)`, 50, y);
    y += 16;

    if (evLogs.length === 0) {
      doc.font('Helvetica').fontSize(8).fillColor(COLORS.muted).text('No custody events recorded.', 58, y);
    } else {
      // Chain header
      doc.rect(50, y, pageWidth, 16).stroke(COLORS.border);
      ['Timestamp', 'Action', 'Performed By', 'Reason'].forEach((h, i) => {
        const xs = [56, 175, 280, 370];
        doc.font('Helvetica-Bold').fontSize(7.5).fillColor(COLORS.primary).text(h, xs[i], y + 4);
      });
      y += 16;

      evLogs
        .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt))
        .forEach((log, i) => {
          if (y > doc.page.height - 60) { doc.addPage(); y = 50; }
          if (i % 2 === 0) doc.rect(50, y, pageWidth, 16).fill('#f6f6f6');
          const performer = log.performedBy?.name || String(log.performedBy);
          const cols2 = [
            new Date(log.createdAt).toLocaleString(),
            log.action.toUpperCase(),
            performer,
            log.reason || '—',
          ];
          const xs = [56, 175, 280, 370];
          const ws = [115, 100, 85, pageWidth - 325];
          cols2.forEach((val, ci) => {
            doc.font('Helvetica').fontSize(7.5).fillColor('#222')
              .text(String(val), xs[ci], y + 4, { width: ws[ci], ellipsis: true });
          });
          y += 16;
        });
    }
  });

  // ── FOOTER ───────────────────────────────────────────────────────────────
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.font('Helvetica').fontSize(7).fillColor(COLORS.muted)
      .text(
        `Digital Evidence Chain of Custody System (DECS) — CONFIDENTIAL — Page ${i + 1} of ${pages.count} — Generated ${new Date().toUTCString()}`,
        50,
        doc.page.height - 30,
        { align: 'center', width: pageWidth }
      );
  }

  doc.end();
};

module.exports = { generateForensicPDF };
